name: Role Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment"
        required: true
        type: choice
        options:
          - dev
          - prod
jobs:
  trigger-platform-cicd:
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}

    permissions:
      contents: read

    steps:
      - name: Trigger platform CI/CD
        env:
          GH_TOKEN: ${{ secrets.CICD_TRIGGER_TOKEN }}
          DATABRICKS_ID: ${{ vars.DATABRICKS_ID }}
        run: |
          jq -n \
            --arg ref "main" \
            --arg target_repository "Housing-Intelligence/hi-role-management" \
            --arg terraform_directory "roles" \
            --arg environment "$DEPLOY_ENV" \
            --arg parameters_json "{\"databricks_external_id\":\"$DATABRICKS_ID\"}" \
            '{
              ref: $ref,
              inputs: {
                target_repository: $target_repository,
                terraform_directory: $terraform_directory,
                environment: $environment,
                parameters_json: $parameters_json
              }
            }' > payload.json

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            https://api.github.com/repos/Housing-Intelligence/hi-platform-cicd/actions/workflows/terraform.yml/dispatches \
            -d @payload.json